AWSTemplateFormatVersion: "2010-09-09"
Description: "Send event from SNS to Lambda. Lambda formats data and send to another SNS."
Resources:
  ToLambdaTopic:
    Type: AWS::SNS::Topic
  FromLambdaTopic:
    Type: AWS::SNS::Topic
  LambdaForFormatServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
  LambdaForFormatServiceRoleDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: sns:publish
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: LambdaForFormatServiceRoleDefaultPolicy
      Roles:
        - Ref: LambdaForFormatServiceRole
  LambdaForFormat:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import os

          import boto3


          def send_sns(message, subject):
              client = boto3.client("sns")
              topic_arn = os.environ["SNS_ARN"]
              client.publish(TopicArn=topic_arn, Message=message, Subject=subject)


          def handler(event, context):
              message = "Hello from lambda!"
              subject = "From  Lambda"
              send_sns(message, subject)
              return {'statusCode': 200}
      Role: !GetAtt LambdaForFormatServiceRole.Arn
      Environment:
        Variables:
          SNS_ARN:
            Ref: FromLambdaTopic
      Handler: index.handler
      Runtime: python3.9
    DependsOn:
      - LambdaForFormatServiceRoleDefaultPolicy
      - LambdaForFormatServiceRole
  LambdaForFormatAllowInvokeCdkSnsLambdaSnsStackToLambdaTopic:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt LambdaForFormat.Arn
      Principal: sns.amazonaws.com
      SourceArn:
        Ref: ToLambdaTopic
  LambdaForFormatToLambdaTopic:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: lambda
      TopicArn:
        Ref: ToLambdaTopic
      Endpoint: !GetAtt LambdaForFormat.Arn
